### ISSUE TITLE
目录问题

### ISSUE THREAD

**Issue by PearsSauce** [Fahaxikiii/napcat-scripts#1]
报错内容：`11-20 22:33:25 [[32minfo[39m] Qmsg酱 | 接收 <- 群聊 [bot群(xxx)] [(xxx)] 大葱 骂我
11-20 22:33:25 [[31merror[39m] Qmsg酱 | 发生错误 Error: ENOENT: no such file or directory, copyfile '/www/wwwroot/xxx/resources/record/dinggong/19.mp3' -> '/app/.config/QQ/NapCat/temp/3f171e13-b49b-4b5b-864e-b7acc9929d1b.mp3'
at Object.copyFileSync (node:fs:3013:11)
at Object.func [as copyFileSync] (node:electron/js2c/node_init:2:2967)
at uri2local (file:///app/napcat/napcat.mjs:19985:17)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async OneBotMsgApi.handleOb11FileLikeMessage (file:///app/napcat/napcat.mjs:50375:9)
at async record (file:///app/napcat/napcat.mjs:50065:8)
at async Promise.all (index 0)
at async OneBotMsgApi.createSendElements (file:///app/napcat/napcat.mjs:50318:17)
at async SendMsg._handle (file:///app/napcat/napcat.mjs:50497:52)
at async SendMsg.websocketHandle (file:///app/napcat/napcat.mjs:41923:23)`

综合看下来貌似是 /app/.config/QQ/NapCat/temp/3f171e13-b49b-4b5b-864e-b7acc9929d1b.mp3 貌似是有问题的

**Comment by Fahaxikiii** [comment]
> 报错内容：`11-20 22:33:25 [�[32minfo�[39m] Qmsg酱 | 接收 <- 群聊 [bot群(xxx)] [(xxx)] 大葱 骂我 11-20 22:33:25 [�[31merror�[39m] Qmsg酱 | 发生错误 Error: ENOENT: no such file or directory, copyfile '/www/wwwroot/xxx/resources/record/dinggong/19.mp3' -> '/app/.config/QQ/NapCat/temp/3f171e13-b49b-4b5b-864e-b7acc9929d1b.mp3' at Object.copyFileSync (node:fs:3013:11) at Object.func [as copyFileSync] (node:electron/js2c/node_init:2:2967) at uri2local (file:///app/napcat/napcat.mjs:19985:17) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async OneBotMsgApi.handleOb11FileLikeMessage (file:///app/napcat/napcat.mjs:50375:9) at async record (file:///app/napcat/napcat.mjs:50065:8) at async Promise.all (index 0) at async OneBotMsgApi.createSendElements (file:///app/napcat/napcat.mjs:50318:17) at async SendMsg._handle (file:///app/napcat/napcat.mjs:50497:52) at async SendMsg.websocketHandle (file:///app/napcat/napcat.mjs:41923:23)`
> 
> 综合看下来貌似是 /app/.config/QQ/NapCat/temp/3f171e13-b49b-4b5b-864e-b7acc9929d1b.mp3 貌似是有问题的

19.mp3所在的目录或者父目录有没有映射到容器内部

**Comment by Mnbqq** [comment]
解决了吗
